### PR TITLE
Set correct number of dimensions for convolve2_nn and convolve2_gradient_nn

### PR DESCRIPTION
**Pull request by c0dearm**
Fixes issue https://github.com/arrayfire/arrayfire-rust/issues/323

### CODE REVIEW

**Comment by 9prady9** [comment]
Sorry about the incorrect fix and thanks for looking into it. Can you please fix the clippy errors.

**Comment by c0dearm** [comment]
@9prady9 those are unrelated to my PR, but I can invest some time fixing them if you wish

**Comment by 9prady9** [comment]
Ah i see, opencl-interop package. If you could fix them quickly, that would be great. I can't get to it right away.

**Comment by c0dearm** [comment]
@9prady9 done!

**Review by 9prady9 — APPROVED** [review]

**Comment by c0dearm** [comment]
I can't merge it because of permissions, please do it yourself @9prady9

**Pull request merged**
