### PR TITLE
Added `get_revision` and `device_info`

### PR DESCRIPTION
**Pull request by botev**
Sorry, this should have been part of the previous, but was a bit busy.
One caveat is that I assumed that the commit string is truly static, so I return `Cow<'static, str>`. Also, I notice that the name of the platform has underscores `Intel(R)_Core(TM)_i7-4600U_CPU_@ 2.10GHz` so the question is should those be replaced by spaces or kept like that.

### CODE REVIEW

**Comment by 9prady9** [comment]
@botev Commit string is a compile time string and the user should not free it. What does `Cow<>` do when a variable of such type goes out of scope ?

@pavanky  Why does the platform name returned by `af_device_info` has underscores?

**Comment by pavanky** [comment]
@9prady9 
> @pavanky Why does the platform name returned by af_device_info has underscores?

I don't know what you mean. Can you show me an example ?

**Comment by 9prady9** [comment]
@pavanky 
```
Name: GeForce_GT_650M
````
Thats the output of `af_devie_info` for platform name, white spaces are replaced by underscores.

**Comment by pavanky** [comment]
@9prady9 That is not platform name, that is device name. I don't remember why I changed spaces to underscores. If we are going to change this, it should probably change upstream.

**Comment by 9prady9** [comment]
Okay. @botev No need to change underscores to white spaces.

**Comment by botev** [comment]
@9prady9 `Cow` is a clone-on-write smart pointer. Additionally, it relies on a reference. This means:
1. It does not free anything underlying (as in rust references require that the owner outlives them, but they do not free resources). 
2. If someone decides to modify it in any way it clones the underlying object. E.g. if someone decides to use the returned value in building a new string it will clone it so that it does not modify the initial underlying string. 

I think that is good consistent behavior and has 0 overhead at runtime (I think the modification checks are at compile time).

**Pull request merged**
