### PR TITLE
Indexing

### LINKED ISSUE #26: passing a str pointer (or even a String) into af::Window::new via a function call results in a GLFWWindow Error for Graphics module
```rust
pub fn plot(raw_values: Vec<f32>, title: &'static str, window_x: u16, window_y: u16) {
  // copy from float vector to Array
  let dims = Dim4::new(&[raw_values.len() as u64, 1, 1, 1]);
  let values = &Array::new(dims, &raw_values.as_ref(), Aftype::F32).unwrap();

  // create a window
  let title_str = String::from(title); // if we don't .clone() we get a crash!
  let wnd = match af::Window::new(window_x as i32, window_y as i32, title_str) {
    Ok(v)  => v,
    Err(e) => panic!("Window creation failed: {}", e), //XXX: handle better
  };

  // display till closed
  loop {
    wnd.draw_plot(&af::range(dims, 0, af::Aftype::F32).unwrap(), &values, None);
    if wnd.is_closed().unwrap() == true { break; }
  }
}
```

results in:

```bash
2015-08-26 14:44:37.785 perceptron[11818:5138515] *** Assertion failure in -[GLFWWindow setTitle:], /SourceCache/AppKit/AppKit-1348.17/AppKit.subproj/NSWindow.m:3068
thread '<main>' panicked at 'Window creation failed: Unkown Error', src/plot.rs:14
An unknown error occurred
```

**Possible solution:** run .clone() internally in the appropriate functions

### LINKED ISSUE #28: Use f32 (or <T>) instead of f64 wherever applicable
An example is:

```rust
    pub fn host(&self, data:&mut [f64]) -> Result<(), AfError> {
```

`f32` is more applicable to video cards as some video cards and generally performs better

### PR DESCRIPTION
**Pull request by jramapuram**
Fixes #28 
Fixes #26

### CODE REVIEW

**Comment by 9prady9** [comment]
This shall be merged after [upstream PR](https://github.com/arrayfire/arrayfire/pull/977) has been merged and pulled in.

**Comment by jramapuram** [comment]
@9prady9 : can you just test the `index_gen()` call before the merge?

**Comment by 9prady9** [comment]
@jramapuram I actually tested the changes in upstream PR with this PR changes already.

**Comment by jramapuram** [comment]
:+1:

**Comment by jramapuram** [comment]
@9prady9 : Can this be merged now since the upstream changes are in? Are there any required modifications to the indexing here so that it conforms to your changes in arrayfire mainline?  I have pushed in the generic type for the af_host function as well.

**Comment by 9prady9** [comment]
@jramapuram Just one last commit from my side. I have it on my local branch on the office machine. Will push it on Monday for sure. I will also update the tag then to `af3.1`.

**Comment by jramapuram** [comment]
Great, thanks!

**Comment by jramapuram** [comment]
:+1:

**Pull request merged**
