### PR TITLE
Add Neural Network Example

### PR DESCRIPTION
**Pull request by MichaelMcCulloch**
This will be my first contribution. I thought this would be the fastest way to get feedback on why my re-implementation of the neural network in rust is so very slow. 

This pr adds the MNIST-rust package to download and unpack the mnist dataset, which is then loaded into arrayfire and processed on the GPU.

If you have any feedback of anykind, I'd love to hear it.

### CODE REVIEW

**Comment by MichaelMcCulloch** [comment]
I just noticed it is ingesting 50K training samples here, whereas the C++ example used a subset of just over 6000, so that would explain the speed decrease.

**Comment by 9prady9** [comment]
> I just noticed it is ingesting 50K training samples here, whereas the C++ example used a subset of just over 6000, so that would explain the speed decrease.

Glad you made some progress, I won't be able to get to it until the weekend. I will let you know if I find anything when I try. Thank you for the contribution and using rust wrapper and arrayfire :)

**Comment by 9prady9** [comment]
@MichaelMcCulloch Does this work as expected after the sample count drop ?

**Comment by 9prady9** [comment]
> 

If it is not an elaborate fix, can you please do it now itself. thanks once again.

**Comment by MichaelMcCulloch** [comment]
There you go! :)

**Review by 9prady9 — CHANGES_REQUESTED** [review]
Can you please fix the below warnings, otherwise looks good to me. Thanks for updating the error calc.

```
warning: unused import: `ArtificialNeuralNetwork`
 --> examples/neural_network.rs:4:11
  |
4 |     ANN::{ArtificialNeuralNetwork, ArtificialNeuralNetworkBuilder},
  |           ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: associated function is never used: `with_initial_random_range`
   --> examples/neural_network.rs:153:16
    |
153 |         pub fn with_initial_random_range(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: module `ANN` should have a snake case name
  --> examples/neural_network.rs:99:5
   |
99 | mod ANN {
   |     ^^^ help: convert the identifier to snake case: `ann`
   |
   = note: `#[warn(non_snake_case)]` on by default
```

**Review by 9prady9 — APPROVED** [review]
thank you @MichaelMcCulloch

**Pull request merged**
